### ISSUE TITLE
facet count update does not work

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/dig-ed-cat-typesense-frontend#11]
if I search in the main search bar e.g. for "Schnitzler" (https://acdh-oeaw.github.io/dig-ed-cat-typesense-frontend/search?q=Schnitzler&page=1) the facets (and their counts) should be updated accordingly, meaning e.g. only the related categories of the resulting three entries should be present in the filters, so for `Historical Period` defenitly no facet for Antiquity

check for example the behavior of https://csae8092.github.io/dig-ed-cat-static/editions.html

**Comment by kaggl** [comment]
Selected facets influencing facet counts is not supported by typesense natively, its also not present in the original static page, so i will close this issue
