### ISSUE TITLE
allow sorting search results

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/dig-ed-cat-typesense-frontend#6]
this probably requires setting `"sort"=true` on some fields in the typesense schema @csae8092 ?

**Comment by kaggl** [comment]
as of now, no field has `"sort"` set to true, I've created an issue that would fix this on the dig-ed-cat-indexer repo (https://github.com/csae8092/dig-ed-cat-indexer/issues/2)

**Comment by csae8092** [comment]
enabled sorting on some fields

**Comment by csae8092** [comment]
sort by id does not work due to some issue with index creation, see https://github.com/csae8092/dig-ed-cat-indexer/issues/6
so this is a backend, not a frontend issue
